### Get all movies
GET http://localhost:5000/api/movies

### Get movie by ID
GET http://localhost:5000/api/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Get movies by genre
GET http://localhost:5000/api/movies?genre=Action

### Create a movie
POST http://localhost:5000/api/movies
Content-Type: application/json

{
    "title": "Oppenheimer",
    "year": 2023 ,
    "director": "Christopher Nolan",
    "duration": 180,
    "poster": "https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_.jpg",
    "genre": ["Drama", "Thriller"],
    "rate": 8.7
}

### Delete movie by ID
DELETE  http://localhost:5000/api/movies/1519b896-4a2c-4d46-beca-78e595c070f6
Content-Type: application/json



### Update movie by ID
PATCH http://localhost:5000/api/movies/cf247152-1f24-4011-9486-d39fe5bc5b99
Content-Type: application/json

{
    "genre": [
        "Drama",
        "Thriller",
        "Action"
]
}
### Get Top 5 Movies
GET http://localhost:5000/api/top-5-movies